---


'.review':
  before_script:
    - 'python -m pip install tox'
  script:
    - 'export TOXENV="${CI_JOB_NAME##review}"'
    - 'python -m tox'
    - 'python -m tox -e package'

'review py37':
  extends: '.review'
  image: 'python:3.7'

'review py38':
  extends: '.review'
  image: 'python:3.8'

'review py39':
  extends: '.review'
  image: 'python:3.9'

'review py310':
  extends: '.review'
  image: 'python:3.10'

'review py311':
  extends: '.review'
  image: 'python:3.11'


...  # EOF
